/**
 * Aetheria: Resonant Horizon - Initial Game Data & World Catalog
 */

import {
  AetherElement,
  WeaponType,
  ItemRarity,
  ItemType,
  EquipmentSlot,
  PlayableCharacter,
  GameItem,
  Quest,
  WaystonePoint,
  NPCData,
  PlayerCustomization,
  GameSaveState,
  Achievement,
  BestiaryEntry,
  CodexLoreEntry,
} from "../types/game";

export const STARTER_CHARACTERS: PlayableCharacter[] = [
  {
    id: "kaelen",
    name: "Kaelen",
    title: "The Windblade",
    element: AetherElement.GALE,
    weaponType: WeaponType.SWORD,
    level: 1,
    exp: 0,
    maxExp: 100,
    ascension: 0,
    stats: {
      hp: 1200,
      maxHp: 1200,
      atk: 145,
      def: 82,
      stamina: 100,
      maxStamina: 100,
      energy: 40,
      maxEnergy: 100,
      critRate: 0.12,
      critDmg: 0.60,
      aetherMastery: 40,
    },
    skillName: "Zephyr Vortex",
    skillDescription: "Slashes forward with compressed wind, pulling enemies together and launching them into the air.",
    skillCooldown: 6,
    ultimateName: "Astral Tempest",
    ultimateDescription: "Unleashes an explosive sphere of emerald wind blades that shreds nearby enemies and enhances movement speed.",
    ultimateEnergyCost: 70,
    avatarColor: "#10b981",
    accentColor: "#34d399",
    bio: "A wandering swordsman of the Sunvale Highlands who learned to listen to the whispers of the wind before the calamity.",
    equipped: {},
  },
  {
    id: "lyra",
    name: "Lyra",
    title: "The Sunfire",
    element: AetherElement.EMBER,
    weaponType: WeaponType.GREATSWORD,
    level: 1,
    exp: 0,
    maxExp: 100,
    ascension: 0,
    stats: {
      hp: 1550,
      maxHp: 1550,
      atk: 185,
      def: 95,
      stamina: 100,
      maxStamina: 100,
      energy: 20,
      maxEnergy: 100,
      critRate: 0.08,
      critDmg: 0.75,
      aetherMastery: 25,
    },
    skillName: "Crimson Cleave",
    skillDescription: "Sweeps a flaming greatsword in a 360-degree arc, dealing explosive Ember damage and heavily staggering targets.",
    skillCooldown: 8,
    ultimateName: "Solar Cataclysm",
    ultimateDescription: "Plunges her blade into the earth, causing molten aether geysers to erupt and leaving a burning trail.",
    ultimateEnergyCost: 80,
    avatarColor: "#ef4444",
    accentColor: "#f87171",
    bio: "Former captain of the Sunvale Vanguard whose blazing aether flame can melt ancient stone.",
    equipped: {},
  },
  {
    id: "zephyr",
    name: "Zephyr",
    title: "The Frostbloom",
    element: AetherElement.BLOOM,
    weaponType: WeaponType.CATALYST,
    level: 1,
    exp: 0,
    maxExp: 100,
    ascension: 0,
    stats: {
      hp: 1100,
      maxHp: 1100,
      atk: 130,
      def: 75,
      stamina: 100,
      maxStamina: 100,
      energy: 50,
      maxEnergy: 100,
      critRate: 0.05,
      critDmg: 0.50,
      aetherMastery: 90,
    },
    skillName: "Verdant Sanctuary",
    skillDescription: "Summons a glowing lotus on the ground that pulses waves of healing to allies and entangles foes.",
    skillCooldown: 10,
    ultimateName: "Wrath of the Earth-Mother",
    ultimateDescription: "Manifests ancient celestial vines that ensnare all surrounding enemies, dealing massive continuous Bloom damage.",
    ultimateEnergyCost: 60,
    avatarColor: "#8b5cf6",
    accentColor: "#a78bfa",
    bio: "A gentle herbalist and mystic scholar attuned to the living pulse of Aetheria's primordial flora.",
    equipped: {},
  },
];

export const STARTER_ITEMS: GameItem[] = [
  {
    id: "wpn_sunvale_blade",
    name: "Sunvale Wanderer's Blade",
    description: "A well-balanced steel sword forged by Sunvale smiths, imbued with trace aether veins.",
    type: ItemType.WEAPON,
    rarity: ItemRarity.RARE,
    weaponType: WeaponType.SWORD,
    slot: EquipmentSlot.WEAPON,
    level: 1,
    maxLevel: 20,
    count: 1,
    statBonus: { atk: 35, critRate: 0.04 },
    iconColor: "#38bdf8",
  },
  {
    id: "wpn_flame_claymore",
    name: "Obsidian Greatsword",
    description: "A heavy blade carved from volcanic rock that retains searing heat.",
    type: ItemType.WEAPON,
    rarity: ItemRarity.RARE,
    weaponType: WeaponType.GREATSWORD,
    slot: EquipmentSlot.WEAPON,
    level: 1,
    maxLevel: 20,
    count: 1,
    statBonus: { atk: 55, def: 15 },
    iconColor: "#f97316",
  },
  {
    id: "wpn_verdant_codex",
    name: "Codex of Whispers",
    description: "An enchanted grimoire whose pages rustle like autumn leaves in the breeze.",
    type: ItemType.WEAPON,
    rarity: ItemRarity.RARE,
    weaponType: WeaponType.CATALYST,
    slot: EquipmentSlot.WEAPON,
    level: 1,
    maxLevel: 20,
    count: 1,
    statBonus: { atk: 30, aetherMastery: 35 },
    iconColor: "#a855f7",
  },
  {
    id: "art_sunvale_crest",
    name: "Crest of the Highlands",
    description: "A silver circlet adorned with an aether crystal that sharpens focus.",
    type: ItemType.EQUIPMENT,
    rarity: ItemRarity.UNCOMMON,
    slot: EquipmentSlot.HEAD,
    level: 1,
    maxLevel: 15,
    count: 1,
    statBonus: { hp: 180, critDmg: 0.06 },
    iconColor: "#eab308",
  },
  {
    id: "art_vanguard_armor",
    name: "Sunvale Leather Tunic",
    description: "Sturdy cuirass reinforced with boiled leather and copper studs.",
    type: ItemType.EQUIPMENT,
    rarity: ItemRarity.UNCOMMON,
    slot: EquipmentSlot.BODY,
    level: 1,
    maxLevel: 15,
    count: 1,
    statBonus: { hp: 260, def: 24 },
    iconColor: "#64748b",
  },
  {
    id: "mat_aether_crystal",
    name: "Aether Crystal Shard",
    description: "Luminescent mineral resonating with raw elemental frequency. Essential for weapon refinement.",
    type: ItemType.MATERIAL,
    rarity: ItemRarity.UNCOMMON,
    count: 8,
    iconColor: "#06b6d4",
  },
  {
    id: "mat_sunvale_herb",
    name: "Sunvale Goldpetal",
    description: "A vibrant mountain flower that blooms in sunny glades. Used for healing elixirs.",
    type: ItemType.MATERIAL,
    rarity: ItemRarity.COMMON,
    count: 12,
    iconColor: "#84cc16",
  },
  {
    id: "con_vitality_brew",
    name: "Elixir of Vitality",
    description: "A shimmering draught brewed from Goldpetals. Instantly restores 450 HP.",
    type: ItemType.CONSUMABLE,
    rarity: ItemRarity.COMMON,
    count: 5,
    buffEffect: { type: "heal", value: 450 },
    iconColor: "#22c55e",
  },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: "main_01",
    title: "Echoes of the Horizon",
    category: "Main Story",
    description: "Speak with Elder Thorne in Sunvale Haven to understand the awakening tremor shaking the plateau.",
    locationName: "Sunvale Haven",
    objectives: [
      { id: "obj_talk_thorne", description: "Talk to Elder Thorne in Sunvale Haven", targetCount: 1, currentCount: 0, completed: false },
    ],
    rewards: {
      exp: 120,
      currency: 200,
    },
    status: "active",
    npcGiver: "thorne",
  },
  {
    id: "main_02",
    title: "Cleansing the Whispering Glade",
    category: "Main Story",
    description: "Corrupted Aetherling beasts have emerged in the glade. Defeat them to protect the trade trail.",
    locationName: "Whispering Glade",
    objectives: [
      { id: "obj_defeat_beasts", description: "Defeat Aetherling Stalkers in the Glade", targetCount: 3, currentCount: 0, completed: false },
    ],
    rewards: {
      exp: 250,
      currency: 400,
    },
    status: "available",
    npcGiver: "thorne",
  },
  {
    id: "main_03",
    title: "Trial of the First Beacon",
    category: "Main Story",
    description: "Activate the three ancient elemental pillars in the ruins to unveil the hidden crypt entrance.",
    locationName: "Ruins of the First Beacon",
    objectives: [
      { id: "obj_activate_pillars", description: "Activate the 3 Ancient Aether Totems (Gale, Ember, Volt)", targetCount: 3, currentCount: 0, completed: false },
    ],
    rewards: {
      exp: 400,
      currency: 600,
    },
    status: "available",
  },
  {
    id: "main_04",
    title: "Wrath of the Ignis-Titan",
    category: "Main Story",
    description: "Enter the Caldera and defeat the ancient volcanic guardian: Resonant Colossus.",
    locationName: "Molten Caldera",
    objectives: [
      { id: "obj_defeat_boss", description: "Defeat the Resonant Colossus: Ignis-Titan", targetCount: 1, currentCount: 0, completed: false },
    ],
    rewards: {
      exp: 1000,
      currency: 1500,
    },
    status: "available",
  },
  {
    id: "side_01",
    title: "Herbalist's Bounty",
    category: "Side Quest",
    description: "Gather Sunvale Goldpetals for Seraphina so she can prepare restorative draughts.",
    locationName: "Whispering Glade",
    objectives: [
      { id: "obj_gather_herbs", description: "Collect Sunvale Goldpetals", targetCount: 4, currentCount: 0, completed: false },
    ],
    rewards: {
      exp: 150,
      currency: 250,
    },
    status: "available",
    npcGiver: "seraphina",
  },
];

export const NPCS: NPCData[] = [
  {
    id: "thorne",
    name: "Elder Thorne",
    role: "Sunvale Elder & Chronicler",
    region: "Sunvale Haven",
    position: [0, 0, -10],
    dialogue: {
      greeting: "Greetings, traveler of the resonant stars. The ley-lines of Sunvale tremble with unfamiliar energy. Have you come to investigate the ancient beacon?",
      options: [
        {
          label: "Tell me about the Aether Tremors.",
          response: "Centuries ago, the Sky Realm sealed the primordial Titans beneath crystalline seals. Now, the elemental seals are weakening. The beasts in the Whispering Glade grow agitated.",
        },
        {
          label: "How do I master the Aether Affinities?",
          response: "Remember the resonance harmony! Strike an enemy with Ember, then touch them with Bloom to trigger a violent Conflagration! Or combine Tide with Volt to chain lightning between all nearby adversaries.",
        },
        {
          label: "I am ready to aid the village. (Progress Quest)",
          response: "May the horizon guide your blade. Head east across the river into Whispering Glade and clear the encroaching Aetherlings.",
          action: "start_quest",
          questId: "main_02",
        },
      ],
    },
  },
  {
    id: "seraphina",
    name: "Seraphina",
    role: "Master Alchemist",
    region: "Sunvale Haven",
    position: [12, 0, -8],
    dialogue: {
      greeting: "Ah, welcome to my apothecary hearth! The soil here produces the most aromatic lumina flora. Are you looking to brew elixirs or stock up on potions?",
      options: [
        {
          label: "Open Alchemy & Cooking Hearth",
          response: "Feel free to use the hearth! Combine gathered flora and crystals to enhance your vitality and combat endurance.",
          action: "open_crafting",
        },
        {
          label: "Do you have any tasks for an adventurer?",
          response: "Indeed! If you venture into the glades, please gather some wild Sunvale Goldpetals for my draughts.",
          action: "start_quest",
          questId: "side_01",
        },
      ],
    },
  },
  {
    id: "gerald",
    name: "Gerald the Smith",
    role: "Vanguard Blacksmith",
    region: "Sunvale Haven",
    position: [-14, 0, -6],
    dialogue: {
      greeting: "Clang, clang! Good steel and true aether make the difference between victory and becoming golem fodder. Need your equipment honed?",
      options: [
        {
          label: "Tell me about equipment refinement.",
          response: "Bring me Aether Crystals from the cliffs and ore deposits. Refined weapons gain bonus attack and critical resonance!",
        },
        {
          label: "What weapons work best against the Titans?",
          response: "Heavy Greatswords like Lyra's can shatter a golem's stagger meter in seconds. Once they're stunned, switch to swift blade combos to deal maximum punishment!",
        },
      ],
    },
  },
  {
    id: "sylas",
    name: "Sylas the Explorer",
    role: "Highland Cartographer",
    region: "Whispering Glade Edge",
    position: [35, 0, 15],
    dialogue: {
      greeting: "Look at this panoramic view! Beyond these cliffs lie the Ancient Ruins and the dormant Molten Caldera. Keep your eyes sharp for hidden treasure chests!",
      options: [
        {
          label: "Any tips on finding hidden chests?",
          response: "Look around ancient pillars and behind waterfalls. Some chests are locked behind elemental totems—match the pillar's glowing rune with your characters' skills to unlock them!",
        },
        {
          label: "How does the Waystone network work?",
          response: "Approach any ancient Waystone pillar and resonate with it. Once unlocked, you can fast-travel across the map instantaneously via your World Map [M]!",
        },
      ],
    },
  },
];

export const WAYSTONES: WaystonePoint[] = [
  {
    id: "way_haven",
    name: "Sunvale Haven Plaza",
    region: "Sunvale Haven",
    position: [0, 0, -2],
    unlocked: true,
    description: "The peaceful heart of Sunvale, watched over by the ancient village windmill.",
  },
  {
    id: "way_glade",
    name: "Whispering Glade Crossing",
    region: "Whispering Glade",
    position: [40, 0, 10],
    unlocked: false,
    description: "A verdant clearing where gentle winds carry the scent of goldpetals.",
  },
  {
    id: "way_ruins",
    name: "Ancient Beacon Sanctum",
    region: "Ruins of the First Beacon",
    position: [75, 2, -45],
    unlocked: false,
    description: "Weathered marble arches left by the celestial builders of the First Age.",
  },
  {
    id: "way_caldera",
    name: "Caldera of the Colossus",
    region: "Molten Caldera",
    position: [-65, 4, 60],
    unlocked: false,
    description: "A scorched volcanic crater where the slumbering Ignis-Titan awaits worthy challengers.",
  },
];

export const DEFAULT_PLAYER_PROFILE: PlayerCustomization = {
  name: "Aetherial Seeker",
  bodyType: "Aetherial Scout",
  hairStyle: "Spiky Breeze",
  hairColor: "#38bdf8",
  eyeColor: "#10b981",
  skinTone: "#fcd34d",
  outfitVariant: "Sunvale Wanderer",
};

export const INITIAL_SAVE_STATE: GameSaveState = {
  version: 1,
  playerId: "player_" + Math.random().toString(36).substring(2, 9),
  playerProfile: DEFAULT_PLAYER_PROFILE,
  party: STARTER_CHARACTERS,
  activeCharacterIndex: 0,
  currency: 500,
  inventory: STARTER_ITEMS,
  quests: INITIAL_QUESTS,
  activeQuestId: "main_01",
  unlockedWaystones: ["way_haven"],
  openedChests: [],
  collectedNodes: {},
  worldTime: {
    hour: 10,
    minute: 30,
    timeScale: 60, // 1 min real = 1 hr game
    phase: "Day",
    weather: "Clear",
  },
  reputation: {
    "Sunvale Highlands": 100,
  },
  defeatedBosses: [],
  lastSaved: Date.now(),
};

export const INITIAL_CHARACTERS = STARTER_CHARACTERS;
export const INITIAL_ITEMS = STARTER_ITEMS;
export const INITIAL_NPCS = NPCS;

export const INITIAL_RECIPES = [
  {
    id: "recipe_elixir",
    name: "Elixir of Vitality",
    category: "Alchemy",
    description: "A shimmering restorative draught brewed from Sunvale Goldpetals and Aether Crystals. Restores 500 HP immediately.",
    ingredients: [
      { itemId: "mat_sunvale_herb", count: 2 },
      { itemId: "mat_aether_crystal", count: 1 },
    ],
    outputItemId: "con_vitality_brew",
    outputCount: 1,
  },
  {
    id: "recipe_swiftfoot",
    name: "Swiftfoot Draught",
    category: "Alchemy",
    description: "Infuses the drinker with wind resonance, increasing movement speed and stamina recovery for 45 seconds.",
    ingredients: [
      { itemId: "mat_sunvale_herb", count: 2 },
      { itemId: "mat_aether_shards", count: 2 },
    ],
    outputItemId: "con_swiftfoot",
    outputCount: 1,
  },
  {
    id: "recipe_surge",
    name: "Resonant Surge Concoction",
    category: "Alchemy",
    description: "A potent high-density aether draft granting +40% Critical Rate and instant 50 Energy to active character.",
    ingredients: [
      { itemId: "mat_aether_crystal", count: 2 },
      { itemId: "mat_aether_shards", count: 3 },
    ],
    outputItemId: "con_surge",
    outputCount: 1,
  },
  {
    id: "recipe_ward",
    name: "Ignis Ward Brew",
    category: "Alchemy",
    description: "Specialized resistance draught protecting against scorching volcanic magma and Ignis-Titan cleaves.",
    ingredients: [
      { itemId: "mat_magma_ore", count: 1 },
      { itemId: "mat_sunvale_herb", count: 2 },
    ],
    outputItemId: "con_ignis_ward",
    outputCount: 1,
  },
];

export const CRAFTING_RECIPES = INITIAL_RECIPES;

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: "ach_awaken",
    title: "Echoes of the Horizon",
    description: "Awaken in the Sunvale Highlands and attune to your primary resonance.",
    category: "Story",
    rewardGold: 100,
    rewardPrisms: 20,
    progress: 1,
    maxProgress: 1,
    completed: true,
    claimed: false,
    icon: "Compass",
  },
  {
    id: "ach_waystone",
    title: "Leyline Attunement",
    description: "Attune and unlock an ancient Fast Travel Waystone.",
    category: "Exploration",
    rewardGold: 200,
    rewardPrisms: 30,
    progress: 1,
    maxProgress: 1,
    completed: true,
    claimed: false,
    icon: "MapPin",
  },
  {
    id: "ach_stalker_hunter",
    title: "Aether Stalker Scourge",
    description: "Defeat 3 wandering Aetherling Stalkers in the Glade or Ruins.",
    category: "Combat",
    rewardGold: 300,
    rewardPrisms: 40,
    progress: 0,
    maxProgress: 3,
    completed: false,
    claimed: false,
    icon: "Swords",
  },
  {
    id: "ach_elemental_harmony",
    title: "Elemental Alchemist",
    description: "Trigger 3 distinct elemental resonance reactions in battle.",
    category: "Combat",
    rewardGold: 250,
    rewardPrisms: 35,
    progress: 0,
    maxProgress: 3,
    completed: false,
    claimed: false,
    icon: "Zap",
  },
  {
    id: "ach_slay_titan",
    title: "Bane of the Molten Core",
    description: "Topple the Ignis-Titan World Boss in the Caldera Arena.",
    category: "Boss",
    rewardGold: 1000,
    rewardPrisms: 100,
    progress: 0,
    maxProgress: 1,
    completed: false,
    claimed: false,
    icon: "Flame",
  },
  {
    id: "ach_master_alchemy",
    title: "Sunvale Apothecary",
    description: "Synthesize an elixir or combat draught at the Hearth.",
    category: "Collection",
    rewardGold: 150,
    rewardPrisms: 25,
    progress: 0,
    maxProgress: 1,
    completed: false,
    claimed: false,
    icon: "FlaskConical",
  },
  {
    id: "ach_pioneer_explorer",
    title: "Cartographer of Aetheria",
    description: "Visit all 4 designated regional landmarks across the Highlands.",
    category: "Exploration",
    rewardGold: 400,
    rewardPrisms: 50,
    progress: 1,
    maxProgress: 4,
    completed: false,
    claimed: false,
    icon: "Globe",
  },
  {
    id: "ach_ascension",
    title: "Resonance Limit Break",
    description: "Ascend any character to increase level cap and unlock passive mastery.",
    category: "Character",
    rewardGold: 500,
    rewardPrisms: 60,
    progress: 0,
    maxProgress: 1,
    completed: false,
    claimed: false,
    icon: "ShieldAlert",
  },
];

export const INITIAL_BESTIARY: BestiaryEntry[] = [
  {
    id: "boss_titan",
    name: "Ignis-Titan",
    title: "Primal Molten Colossus",
    category: "World Boss",
    habitat: "Molten Caldera Arena",
    element: AetherElement.EMBER,
    weakness: AetherElement.TIDE,
    drops: ["Calamity Core", "Heart of Ignis", "5★ Volcanic Crown", "500x Aether Shards"],
    lore: "An ancient subterranean entity awakened when the Ley Line ruptured. Encased in cooling obsidian plates, it channels raw magma from the planet's mantle and periodically enters an incandescent overcharge state.",
    defeatedCount: 0,
    combatTips: "Use Tide attacks to trigger rapid cooling and deplete its Stagger Meter. When it rears back for its Caldera Slam, dodge through the shockwave using right-click to trigger a Perfect Dodge slowdown.",
    dangerLevel: 5,
  },
  {
    id: "stalker",
    name: "Aetherling Stalker",
    title: "Glade Prowler",
    category: "Wild Aetherling",
    habitat: "Whispering Glade & Ruins",
    element: AetherElement.GALE,
    weakness: AetherElement.EMBER,
    drops: ["Stalker Feather", "Aether Crystal Fragment", "Aether Shards"],
    lore: "Corrupted avians warped by excess atmospheric wind aether. They glide soundlessly above the tall grasses, pouncing on lone explorers with razor-sharp gale talons.",
    defeatedCount: 0,
    combatTips: "Susceptible to Ember fire damage. Hitting them with fire while in mid-leap triggers Conflagration, knocking them to the earth.",
    dangerLevel: 2,
  },
  {
    id: "automaton",
    name: "Beacon Sentry",
    title: "Ancient Ley Automaton",
    category: "Automaton",
    habitat: "Ruins of the First Beacon",
    element: AetherElement.STONE,
    weakness: AetherElement.VOLT,
    drops: ["Ancient Gear", "Power Core", "Reinforced Chassis Plating"],
    lore: "Mechanical custodians engineered by the vanished Precursor architects. Though thousands of years old, their crystalline gyros still rotate tirelessly to eradicate intruders.",
    defeatedCount: 0,
    combatTips: "Their heavy basalt armor resists physical slashing. Discharge Volt attacks to short-circuit their power cores and trigger Overload.",
    dangerLevel: 3,
  },
  {
    id: "glade_sprite",
    name: "Verdant Glade Sprite",
    title: "Flora Manifestation",
    category: "Wild Aetherling",
    habitat: "Sunvale Grasslands & Riverbanks",
    element: AetherElement.BLOOM,
    weakness: AetherElement.EMBER,
    drops: ["Sunvale Pollen", "Dew of Vitality", "Green Fiber"],
    lore: "Gentle spirits coalesced from the fragrance of Sunvale Goldpetals. While normally docile, they defend sacred groves by firing bursts of sharp thorn needles.",
    defeatedCount: 0,
    combatTips: "Easily dispatched with swift fire cleaves. Defeating them occasionally yields rare alchemical restorative reagents.",
    dangerLevel: 1,
  },
];

export const INITIAL_CODEX: CodexLoreEntry[] = [
  {
    id: "codex_factions_order",
    title: "The Resonant Order",
    category: "Factions",
    preview: "Scholars, knights, and oracles sworn to protect the Celestial Ley Lines.",
    content: "Established five hundred years after the Great Shattering, the Resonant Order operates out of the Grand Spires. They classify human affinity into six resonant aether paths and maintain the Waystones that connect disparate sanctuaries.",
    unlocked: true,
    unlockedBy: "Default Traveler Record",
  },
  {
    id: "codex_factions_pioneers",
    title: "Sunvale Pioneers & Settlers",
    category: "Factions",
    preview: "Hardy farmers, alchemists, and builders carving out life in the highlands.",
    content: "Led by village Elder Thorne and Master Blacksmith Gerald, the pioneers of Sunvale Haven built high-velocity windmills to tap into the perennial breezes of the cliffs. They trade herbs, honey, and crafted aether charms.",
    unlocked: true,
    unlockedBy: "Visited Sunvale Haven",
  },
  {
    id: "codex_regions_haven",
    title: "Sunvale Haven & The Windmill Meadows",
    category: "Regions",
    preview: "A peaceful sanctuary perched atop the limestone bluffs of the eastern coast.",
    content: "Known for its golden meadows, cobblestone hearths, and the gentle chime of prayer bells. Travelers frequently begin their expedition here, stocking up on fresh Vitality Draughts before heading into the wild glades.",
    unlocked: true,
    unlockedBy: "Explored Sunvale Haven",
  },
  {
    id: "codex_regions_ruins",
    title: "Ruins of the First Beacon",
    category: "Regions",
    preview: "Weathered marble arches and subterranean vaults from the First Era.",
    content: "Centuries before modern history began, an ancient civilization erected colossal elemental beacons to regulate planetary mana. Now crumbling under ivy and moss, the ruins still hum with dormant power.",
    unlocked: true,
    unlockedBy: "Approached the Ancient Beacon",
  },
  {
    id: "codex_regions_caldera",
    title: "The Molten Caldera",
    category: "Regions",
    preview: "A scorched volcanic crater where the tectonic plates bleed liquid aether.",
    content: "The epicenter of the regional disturbance. Boiling basalt and plumes of sulfuric smoke blanket the skies. At its center lies the slumbering Ignis-Titan, an elemental leviathan whose awakening threatens all of Sunvale.",
    unlocked: false,
    unlockedBy: "Enter the Caldera Arena",
  },
  {
    id: "codex_history_shattering",
    title: "The Day the Heavens Fractured",
    category: "History",
    preview: "Historical accounts of the cataclysm that gave birth to modern Aetheria.",
    content: "According to astral inscriptions, the sky cracked like glass during the Zenith Convergence. The crystalline heavens rained shards across the continents, fusing mortal spirits with elemental currents.",
    unlocked: true,
    unlockedBy: "Consulted the Ancient Oracle",
  },
  {
    id: "codex_mysteries_prisms",
    title: "Astral Prisms of the High Void",
    category: "Mysteries",
    preview: "Luminescent cosmic gems said to hold the resonance of distant stellar bodies.",
    content: "Astral Prisms do not originate from terrestrial mines. They condense from high-altitude aurora borealis events and can be used to attune weapons to legendary frequencies or forge pacts with wandering astral spirits.",
    unlocked: true,
    unlockedBy: "Unlocked Achievement System",
  },
];

